//! Static rule definitions mapping shell commands to their Mycelium equivalents.
use super::report::MyceliumStatus;

/// A rule mapping a shell command pattern to its Mycelium equivalent.
pub struct MyceliumRule {
    pub mycelium_cmd: &'static str,
    /// Original command prefixes to replace with mycelium_cmd (longest first for correct matching).
    pub rewrite_prefixes: &'static [&'static str],
    pub category: &'static str,
    pub savings_pct: f64,
    pub subcmd_savings: &'static [(&'static str, f64)],
    pub subcmd_status: &'static [(&'static str, MyceliumStatus)],
}

/// Regex patterns for matching shell commands, ordered to align with `RULES` by index.
pub const PATTERNS: &[&str] = &[
    r"^git\s+(status|log|diff|show|add|commit|push|pull|branch|fetch|stash|worktree|rebase|merge|checkout|switch|restore|reset|cherry-pick|tag|remote|clone)",
    r"^gh\s+(pr|issue|run|repo|api|release)",
    r"^cargo\s+(build|test|clippy|check|fmt|install|nextest)",
    r"^pnpm\s+(list|ls|outdated|install)",
    r"^npm\s+(run|exec)",
    r"^npx\s+",
    r"^(cat|head|tail)\s+",
    r"^(rg|grep|egrep|fgrep)\s+",
    r"^ls(\s|$)",
    r"^find\s+",
    r"^(npx\s+|pnpm\s+|bunx\s+|bun\s+run\s+|yarn\s+exec\s+|yarn\s+dlx\s+|pnpm\s+exec\s+|pnpm\s+dlx\s+)?tsc(\s|$)",
    r"^(npx\s+|pnpm\s+|bunx\s+|bun\s+run\s+|yarn\s+exec\s+|yarn\s+dlx\s+|pnpm\s+exec\s+|pnpm\s+dlx\s+)?(eslint|biome|lint)(\s|$)",
    r"^(npx\s+|pnpm\s+|bunx\s+|bun\s+run\s+|yarn\s+exec\s+|yarn\s+dlx\s+|pnpm\s+exec\s+|pnpm\s+dlx\s+)?prettier",
    r"^(npx\s+|pnpm\s+|bunx\s+|bun\s+run\s+|yarn\s+exec\s+|yarn\s+dlx\s+|pnpm\s+exec\s+|pnpm\s+dlx\s+)?next\s+build",
    r"^(npx\s+|pnpm\s+|bunx\s+|bun\s+run\s+|yarn\s+exec\s+|yarn\s+dlx\s+|pnpm\s+exec\s+|pnpm\s+dlx\s+)?(vitest|jest|test)(\s|$)",
    r"^(npx\s+|pnpm\s+|bunx\s+|bun\s+run\s+|yarn\s+exec\s+|yarn\s+dlx\s+|pnpm\s+exec\s+|pnpm\s+dlx\s+)?playwright",
    r"^(npx\s+|pnpm\s+|bunx\s+|bun\s+run\s+|yarn\s+exec\s+|yarn\s+dlx\s+|pnpm\s+exec\s+|pnpm\s+dlx\s+)?prisma",
    r"^(docker|podman)\s+(ps|images|logs|run|exec|build|compose\s+(ps|logs|build))",
    r"^kubectl\s+(get|logs|describe|apply)",
    r"^tree(\s|$)",
    r"^diff\s+",
    r"^diffsitter\s+",
    r"^curl\s+",
    r"^wget\s+",
    r"^(python3?\s+-m\s+)?mypy(\s|$)",
    // Python tooling
    r"^ruff\s+(check|format)",
    r"^(python3?\s+-m\s+)?pytest(\s|$)",
    r"^(python3?\s+-m\s+)?(pip3?|uv\s+pip)\s+(list|outdated|install)",
    // Go tooling
    r"^go\s+(test|build|vet)",
    r"^golangci-lint(\s|$)",
    // AWS CLI
    r"^aws\s+",
    // PostgreSQL
    r"^psql(\s|$)",
    // Terraform / OpenTofu
    r"^(terraform|tofu|opentofu)\s+(plan|apply|init|show|output|destroy|validate|fmt)",
    r"^atmos\s+(terraform|describe|validate|workflow|version)",
];

/// Static rule table mapping shell commands to their Mycelium equivalents and savings estimates.
pub const RULES: &[MyceliumRule] = &[
    MyceliumRule {
        mycelium_cmd: "mycelium git",
        rewrite_prefixes: &["git"],
        category: "Git",
        savings_pct: 70.0,
        subcmd_savings: &[
            ("diff", 80.0),
            ("show", 80.0),
            ("add", 59.0),
            ("commit", 59.0),
        ],
        subcmd_status: &[
            ("checkout", MyceliumStatus::Passthrough),
            ("switch", MyceliumStatus::Passthrough),
            ("restore", MyceliumStatus::Passthrough),
            ("reset", MyceliumStatus::Passthrough),
            ("cherry-pick", MyceliumStatus::Passthrough),
            ("clone", MyceliumStatus::Passthrough),
            ("remote", MyceliumStatus::Passthrough),
            ("tag", MyceliumStatus::Passthrough),
        ],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium gh",
        rewrite_prefixes: &["gh"],
        category: "GitHub",
        savings_pct: 82.0,
        subcmd_savings: &[("pr", 87.0), ("run", 82.0), ("issue", 80.0)],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium cargo",
        rewrite_prefixes: &["cargo"],
        category: "Cargo",
        savings_pct: 80.0,
        subcmd_savings: &[("test", 90.0), ("nextest", 90.0), ("check", 80.0)],
        subcmd_status: &[("fmt", MyceliumStatus::Passthrough)],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium pnpm",
        rewrite_prefixes: &["pnpm"],
        category: "PackageManager",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium npm",
        rewrite_prefixes: &["npm"],
        category: "PackageManager",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium npx",
        rewrite_prefixes: &["npx"],
        category: "PackageManager",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium read",
        rewrite_prefixes: &["cat", "head", "tail"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium grep",
        rewrite_prefixes: &["rg", "egrep", "fgrep", "grep"],
        category: "Files",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium ls",
        rewrite_prefixes: &["ls"],
        category: "Files",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium find",
        rewrite_prefixes: &["find"],
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        // Longest prefixes first for correct matching
        mycelium_cmd: "mycelium tsc",
        rewrite_prefixes: &[
            "pnpm exec tsc",
            "pnpm dlx tsc",
            "yarn exec tsc",
            "yarn dlx tsc",
            "bun run tsc",
            "bunx tsc",
            "pnpm tsc",
            "npx tsc",
            "tsc",
        ],
        category: "Build",
        savings_pct: 83.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium lint",
        rewrite_prefixes: &[
            "pnpm exec eslint",
            "pnpm dlx eslint",
            "yarn exec eslint",
            "yarn dlx eslint",
            "bun run eslint",
            "bunx eslint",
            "pnpm exec biome",
            "pnpm dlx biome",
            "yarn exec biome",
            "yarn dlx biome",
            "bun run biome",
            "bunx biome",
            "npx eslint",
            "pnpm lint",
            "npx biome",
            "eslint",
            "biome",
            "lint",
        ],
        category: "Build",
        savings_pct: 84.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium prettier",
        rewrite_prefixes: &[
            "pnpm exec prettier",
            "pnpm dlx prettier",
            "yarn exec prettier",
            "yarn dlx prettier",
            "bun run prettier",
            "bunx prettier",
            "npx prettier",
            "pnpm prettier",
            "prettier",
        ],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        // "next build" is stripped to "mycelium next" — the build subcommand is internal
        mycelium_cmd: "mycelium next",
        rewrite_prefixes: &[
            "pnpm exec next build",
            "pnpm dlx next build",
            "yarn exec next build",
            "yarn dlx next build",
            "bun run next build",
            "bunx next build",
            "npx next build",
            "pnpm next build",
            "next build",
        ],
        category: "Build",
        savings_pct: 87.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium vitest",
        rewrite_prefixes: &[
            "pnpm exec vitest",
            "pnpm dlx vitest",
            "yarn exec vitest",
            "yarn dlx vitest",
            "bun run vitest",
            "bunx vitest",
            "pnpm exec jest",
            "pnpm dlx jest",
            "yarn exec jest",
            "yarn dlx jest",
            "bun run jest",
            "bunx jest",
            "pnpm vitest",
            "npx vitest",
            "vitest",
            "jest",
        ],
        category: "Tests",
        savings_pct: 99.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium playwright",
        rewrite_prefixes: &[
            "pnpm exec playwright",
            "pnpm dlx playwright",
            "yarn exec playwright",
            "yarn dlx playwright",
            "bun run playwright",
            "bunx playwright",
            "npx playwright",
            "pnpm playwright",
            "playwright",
        ],
        category: "Tests",
        savings_pct: 94.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium prisma",
        rewrite_prefixes: &[
            "pnpm exec prisma",
            "pnpm dlx prisma",
            "yarn exec prisma",
            "yarn dlx prisma",
            "bun run prisma",
            "bunx prisma",
            "npx prisma",
            "pnpm prisma",
            "prisma",
        ],
        category: "Build",
        savings_pct: 88.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium docker",
        rewrite_prefixes: &["podman", "docker"],
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium kubectl",
        rewrite_prefixes: &["kubectl"],
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium tree",
        rewrite_prefixes: &["tree"],
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium diff",
        rewrite_prefixes: &["diff"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium diff",
        rewrite_prefixes: &["diffsitter"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium curl",
        rewrite_prefixes: &["curl"],
        category: "Network",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium wget",
        rewrite_prefixes: &["wget"],
        category: "Network",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium mypy",
        rewrite_prefixes: &["python3 -m mypy", "python -m mypy", "mypy"],
        category: "Build",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    // Python tooling
    MyceliumRule {
        mycelium_cmd: "mycelium ruff",
        rewrite_prefixes: &["ruff"],
        category: "Python",
        savings_pct: 80.0,
        subcmd_savings: &[("check", 80.0), ("format", 75.0)],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium pytest",
        rewrite_prefixes: &["python3 -m pytest", "python -m pytest", "pytest"],
        category: "Python",
        savings_pct: 90.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium pip",
        rewrite_prefixes: &["python3 -m pip", "python -m pip", "pip3", "pip", "uv pip"],
        category: "Python",
        savings_pct: 75.0,
        subcmd_savings: &[("list", 75.0), ("outdated", 80.0)],
        subcmd_status: &[],
    },
    // Go tooling
    MyceliumRule {
        mycelium_cmd: "mycelium go",
        rewrite_prefixes: &["go"],
        category: "Go",
        savings_pct: 85.0,
        subcmd_savings: &[("test", 90.0), ("build", 80.0), ("vet", 75.0)],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium golangci-lint",
        rewrite_prefixes: &["golangci-lint", "golangci"],
        category: "Go",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    // AWS CLI
    MyceliumRule {
        mycelium_cmd: "mycelium aws",
        rewrite_prefixes: &["aws"],
        category: "Infra",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    // PostgreSQL
    MyceliumRule {
        mycelium_cmd: "mycelium psql",
        rewrite_prefixes: &["psql"],
        category: "Infra",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    // Terraform / OpenTofu
    MyceliumRule {
        mycelium_cmd: "mycelium terraform",
        rewrite_prefixes: &["opentofu", "tofu", "terraform"],
        category: "Infra",
        savings_pct: 75.0,
        subcmd_savings: &[("plan", 80.0), ("apply", 85.0)],
        subcmd_status: &[],
    },
    MyceliumRule {
        mycelium_cmd: "mycelium atmos",
        rewrite_prefixes: &["atmos"],
        category: "Infra",
        savings_pct: 75.0,
        subcmd_savings: &[("terraform", 80.0), ("describe", 70.0)],
        subcmd_status: &[],
    },
];

/// Commands to ignore (shell builtins, trivial, already mycelium).
pub const IGNORED_PREFIXES: &[&str] = &[
    "cd ",
    "cd\t",
    "echo ",
    "printf ",
    "export ",
    "source ",
    "mkdir ",
    "rm ",
    "mv ",
    "cp ",
    "chmod ",
    "chown ",
    "touch ",
    "which ",
    "type ",
    "command ",
    "test ",
    "true",
    "false",
    "sleep ",
    "wait",
    "kill ",
    "set ",
    "unset ",
    "wc ",
    "sort ",
    "uniq ",
    "tr ",
    "cut ",
    "awk ",
    "sed ",
    "python3 -c",
    "python -c",
    "node -e",
    "ruby -e",
    "mycelium ",
    "pwd",
    "bash ",
    "sh ",
    "then\n",
    "then ",
    "else\n",
    "else ",
    "do\n",
    "do ",
    "for ",
    "while ",
    "if ",
    "case ",
];

/// Exact command strings to ignore (shell builtins with no arguments).
pub const IGNORED_EXACT: &[&str] = &[
    "cd", "echo", "true", "false", "wait", "pwd", "bash", "sh", "fi", "done",
];
